<?php

namespace Leafwrap\MailGateways;

use Illuminate\Contracts\Http\Kernel;
use Illuminate\Support\ServiceProvider;

class MailGatewayServiceProvider extends ServiceProvider
{
    public function boot(Kernel $kernel)
    {
//        $this->loadRoutesFrom(__DIR__ . '/routes/api.php');
        $this->loadMigrationsFrom(__DIR__ . '/migrations');
    }

    public function register(): void
    {
        $this->registerFacades();
        parent::register(); // TODO: Change the autogenerated stub
    }

    protected function registerFacades(): void
    {
        $this->app->singleton('MailGateway', function ($app) {
            return new MailGateway();
        });
    }
}
